source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '4.1.0'
gem 'sqlite3'
gem 'couchrest_model'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'passenger', '4.0.38'
gem 'nokogiri'
gem 'settingslogic', '2.0.9'
#gem 'passenger'
